---
- name: install base system packages
  package: name={{ item }} state=present
  with_items:
    - '{{ cc1plus }}'
    - '{{ libffi_devel }}'
    - '{{ openssl_devel }}'
    - '{{ python3_cython }}'

- name: install base python packages
  pip:
    virtualenv: '{{ virtualenv_folder }}'
    name:
      - crosscompute
      - crosscompute-types
      - requests[security]
  become_user: '{{ target_user }}'
