---
- name: install computational system packages for theano
  package: name={{ item }} state=present
  with_items:
    - '{{ blas_devel }}'
    - '{{ python3_devel }}'

- name: install computational python packages for theano
  pip: virtualenv={{ virtualenv_folder }}
    name:
      - pydot-ng
  become_user: '{{ target_user }}'

- name: install computational python packages
  pip: virtualenv={{ virtualenv_folder }}
    name:
      - networkx
      - scikit-learn
  become_user: '{{ target_user }}'
