---
- name: install spatial system packages
  package: name={{ item }} state=present
  with_items:
    - gdal
    - '{{ gdal_devel }}'
    - '{{ gdal_python3 }}'
    - '{{ geos_devel }}'
    - '{{ proj_data }}'
    - '{{ proj_devel }}'

- name: install spatial python packages
  pip: virtualenv={{ virtualenv_folder }}
    name:
      - shapely[vectorized]
      - geojson
      - geometryIO
      - geopy
      - geotable
  become_user: '{{ target_user }}'
