---
- name: include variables
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_os_family }}.yml'
    - 'RedHat.yml'

- name: install system packages
  package: name={{ item }} state=present
  become: true
  with_items:
    - '{{ redis }}'
    - firewalld
    - nginx
    - nodejs
    - npm
    - policycoreutils-python-utils
    - rubygem-sass

- name: install node packages
  npm: name={{ item }} state=present global=yes
  become: true
  with_items:
    - browserify
    - socket.io@1.6.0
    - uglify-js

- name: install python packages
  pip:
    virtualenv: '{{ virtualenv_folder }}'
    name:
      - archiveIO
      - arrow
      - dogpile.cache
      - flask
      - msgpack-python
      - pyramid
      - pyramid-ipython
      - pyramid-tm
      - pyzmq
      - socketIO-client
      - sphinx
      - sqlalchemy
      - whenIO
      - zope.sqlalchemy
  become: true
  become_user: '{{ target_user }}'
